// <auto-generated />
namespace Sistema_Facturacion.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Facturacion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Facturacion));
        
        string IMigrationMetadata.Id
        {
            get { return "202004041917056_Facturacion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
