// <auto-generated />
namespace Sistema_Facturacion.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Proveedor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Proveedor));
        
        string IMigrationMetadata.Id
        {
            get { return "202004011838525_Proveedor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
